### ISSUE TITLE
International?

### ISSUE THREAD

**Issue by PascalPixel** [xtr3me/spree_shipping_postnl#1]
The readme says national, I'm looking for international through postnl, would this be adjustable?

**Comment by xtr3me** [comment]
Hi Pascal,
As this is a simple calculator i think it won't be hard to adjust it to include international shipments.
But the data has to be available in the [Package](http://www.rubydoc.info/gems/spree_core/Spree/Stock/Package) object. 

What we also can do is make an extra class: PostNlInternational for example and dedicate it to handle international shipments. I think this would be the preferred way.

I'm open for pull requests, or if you can make a table with the needed information in it (dimensions, volume, weight, price) i'm happy to cook something up for you.
